#define SF_WEATHER_ACTIVE (1 << 0)
#define SF_WEATHER_ALLOW_INDOOR (1 << 1)
#define SF_WEATHER_NOT_AFFECTED_BY_WIND (1 << 2)
#define SF_WEATHER_LOCALIZED (1 << 3)
#define SF_WEATHER_DISTANCE_IS_RADIUS (1 << 4)
#define WEATHER_BRUSH_ENTITY (1 << 12)

#define SF_RAIN_ACTIVE SF_WEATHER_ACTIVE
#define SF_RAIN_ALLOW_INDOOR SF_WEATHER_ALLOW_INDOOR
#define SF_RAIN_NOT_AFFECTED_BY_WIND SF_WEATHER_NOT_AFFECTED_BY_WIND
#define SF_RAIN_LOCALIZED SF_WEATHER_LOCALIZED
#define SF_RAIN_DISTANCE_IS_RADIUS SF_WEATHER_DISTANCE_IS_RADIUS
#define SF_RAIN_NO_WIND (1 << 5)
#define SF_RAIN_NO_SPLASHES (1 << 6)
#define SF_RAIN_NO_RIPPLES (1 << 7)
#define RAIN_BRUSH_ENTITY WEATHER_BRUSH_ENTITY
#pragma once

#define SF_SNOW_ACTIVE SF_WEATHER_ACTIVE
#define SF_SNOW_ALLOW_INDOOR SF_WEATHER_ALLOW_INDOOR
#define SF_SNOW_NOT_AFFECTED_BY_WIND SF_WEATHER_NOT_AFFECTED_BY_WIND
#define SF_SNOW_LOCALIZED SF_WEATHER_LOCALIZED
#define SF_SNOW_DISTANCE_IS_RADIUS SF_WEATHER_DISTANCE_IS_RADIUS
#define SNOW_BRUSH_ENTITY WEATHER_BRUSH_ENTITY

enum
{
	PARTICLE_LIGHT_DEFAULT = 0,
	PARTICLE_LIGHT_NONE,
	PARTICLE_LIGHT_COLOR,
	PARTICLE_LIGHT_INTENSITY,
};